//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 10:05:13 AM EST 
//


package com.tresys.jalop.schemas.mil.dod.jalop_1_0.applicationmetadatatypes;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MediaTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MediaTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="application"/>
 *     &lt;enumeration value="audio"/>
 *     &lt;enumeration value="example"/>
 *     &lt;enumeration value="image"/>
 *     &lt;enumeration value="message"/>
 *     &lt;enumeration value="model"/>
 *     &lt;enumeration value="text"/>
 *     &lt;enumeration value="video"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MediaTypeType")
@XmlEnum
public enum MediaTypeType {

    @XmlEnumValue("application")
    APPLICATION("application"),
    @XmlEnumValue("audio")
    AUDIO("audio"),
    @XmlEnumValue("example")
    EXAMPLE("example"),
    @XmlEnumValue("image")
    IMAGE("image"),
    @XmlEnumValue("message")
    MESSAGE("message"),
    @XmlEnumValue("model")
    MODEL("model"),
    @XmlEnumValue("text")
    TEXT("text"),
    @XmlEnumValue("video")
    VIDEO("video");
    private final String value;

    MediaTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MediaTypeType fromValue(String v) {
        for (MediaTypeType c: MediaTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
