//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 10:05:13 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dod.mil/jalop-1.0/applicationMetadataTypes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tresys.jalop.schemas.mil.dod.jalop_1_0.applicationmetadatatypes;
