//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.06 at 10:05:13 AM EST 
//


package com.tresys.jalop.schemas.mil.dod.jalop_1_0.applicationmetadatatypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for TransformType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransformType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.dod.mil/jalop-1.0/applicationMetadataTypes}XOR"/>
 *         &lt;element ref="{http://www.dod.mil/jalop-1.0/applicationMetadataTypes}AES128"/>
 *         &lt;element ref="{http://www.dod.mil/jalop-1.0/applicationMetadataTypes}AES192"/>
 *         &lt;element ref="{http://www.dod.mil/jalop-1.0/applicationMetadataTypes}AES256"/>
 *         &lt;any processContents='lax' namespace='##other'/>
 *       &lt;/choice>
 *       &lt;attribute name="Algorithm" use="required" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransformType", propOrder = {
    "xorOrAES128OrAES192"
})
public class TransformType {

    @XmlElementRefs({
        @XmlElementRef(name = "AES192", namespace = "http://www.dod.mil/jalop-1.0/applicationMetadataTypes", type = JAXBElement.class),
        @XmlElementRef(name = "XOR", namespace = "http://www.dod.mil/jalop-1.0/applicationMetadataTypes", type = JAXBElement.class),
        @XmlElementRef(name = "AES128", namespace = "http://www.dod.mil/jalop-1.0/applicationMetadataTypes", type = JAXBElement.class),
        @XmlElementRef(name = "AES256", namespace = "http://www.dod.mil/jalop-1.0/applicationMetadataTypes", type = JAXBElement.class)
    })
    @XmlAnyElement(lax = true)
    protected List<Object> xorOrAES128OrAES192;
    @XmlAttribute(name = "Algorithm", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String algorithm;

    /**
     * Gets the value of the xorOrAES128OrAES192 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the xorOrAES128OrAES192 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getXOROrAES128OrAES192().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link AES256CBCType }{@code >}
     * {@link Element }
     * {@link JAXBElement }{@code <}{@link AES192CBCType }{@code >}
     * {@link JAXBElement }{@code <}{@link XorECBType }{@code >}
     * {@link JAXBElement }{@code <}{@link AES128CBCType }{@code >}
     * {@link Object }
     * 
     * 
     */
    public List<Object> getXOROrAES128OrAES192() {
        if (xorOrAES128OrAES192 == null) {
            xorOrAES128OrAES192 = new ArrayList<Object>();
        }
        return this.xorOrAES128OrAES192;
    }

    /**
     * Gets the value of the algorithm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlgorithm() {
        return algorithm;
    }

    /**
     * Sets the value of the algorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlgorithm(String value) {
        this.algorithm = value;
    }

}
